use crate::agent_adapter::{AgentAdapter, AgentAdapterEvent, AgentAdapterRunInput};
use crate::protocol::{CadConversationRole, CadSourceLanguage};
use tokio::time::{sleep, Duration};

pub struct FakeAgentAdapter;

#[async_trait::async_trait]
impl AgentAdapter for FakeAgentAdapter {
    fn external_agent(&self) -> &'static str {
        "fake"
    }

    async fn run(&self, input: AgentAdapterRunInput) -> Result<Vec<AgentAdapterEvent>, String> {
        if input.prompt.to_lowercase().contains("fail") || input.prompt.contains("[fail]") {
            return Err("Fake agent adapter failed by prompt request.".to_string());
        }
        sleep(Duration::from_millis(5)).await;
        Ok(vec![
            AgentAdapterEvent::ToolStarted {
                name: "generate_source".to_string(),
            },
            AgentAdapterEvent::SourceUpdated {
                source_language: CadSourceLanguage::Openscad,
                source: build_open_scad_source(&input.prompt),
            },
            AgentAdapterEvent::ToolCompleted {
                name: "generate_source".to_string(),
            },
            AgentAdapterEvent::ToolStarted {
                name: "render_preview".to_string(),
            },
            AgentAdapterEvent::ToolCompleted {
                name: "render_preview".to_string(),
            },
            AgentAdapterEvent::MessageCreated {
                role: CadConversationRole::Assistant,
                content: format!("Created an OpenSCAD preview from: {}", input.prompt),
                metadata: None,
            },
        ])
    }
}

fn build_open_scad_source(prompt: &str) -> String {
    let seed = prompt
        .chars()
        .map(|character| character as u32)
        .sum::<u32>();
    let width = 24 + seed % 28;
    let depth = 18 + seed % 18;
    let height = 10 + seed % 16;
    let radius = 4 + seed % 7;
    let safe_prompt = prompt.replace('\n', " ").replace("*/", "* /");
    format!(
        r#"// Generated by Cadastrophe FakeAgentAdapter
// Prompt: {safe_prompt}
width = {width}; // @param min=8 max=80 step=1 label=Width
depth = {depth}; // @param min=8 max=80 step=1 label=Depth
height = {height}; // @param min=4 max=60 step=1 label=Height
hole_radius = {radius}; // @param min=2 max=16 step=1 label=Hole radius

difference() {{
  cube([width, depth, height], center=true);
  translate([0, 0, -height]) cylinder(h=height * 3, r=hole_radius, center=true);
}}
translate([width * 0.65, 0, height * 0.55]) sphere(r=hole_radius);
"#
    )
}
